#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d code term gimp lutris steam VI VII VIII IX X
bspc monitor DP-2 -d discord brave III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config pointer_follows_focus true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color \#1e1e2e
bspc config active_border_color \#1e1e2e
bspc config focused_border_color \#7480c2






bspc rule -a easyeffects monitor=DP-0 desktop=X
bspc rule -a Pavucontrol state=floating
bspc rule -a discord monitor=DP-2 desktop=discord
bspc rule -a Steam monitor=DP-0 desktop=steam
bspc rule - Brave-browser monitor=brave desktop=brave
bspc rule -a Alacritty monitor=DP-0 desktop=term
bspc rule -a Code monitor=DP=0 desktop=code
bspc rule -a Lutris monitor=DP-0 monitor=lutris
bspc rule -a gimp-2.10 monitor=DP-0 monitor=gimp
bspc rule -a Bitwarden monitor=DP-2 monitor=X 


picom -b &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
/usr/bin/brave-browser  &
/usr/bin/discord &
/usr/games/steam -silent &
/usr/bin/alacritty &
/usr/games/lutris -silent &
/usr/bin/code &
/snap/bin/bitwarden -silent &
/usr/bin/opentabletdriver -silent &
xsetroot -cursor_name left_ptr &

