#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d code term gimp lutris steam VI VII VIII IX X
bspc monitor DP-2 -d discord firefox III IV V VI VII VIII IX X

bspc config external_rules_command "$HOME/bin/bspwm-external-rules"
bspc config border_width 0
bspc config window_gap 0
bspc config split_ratio 0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config normal_border_color \#1e1e2e
bspc config active_border_color \#1e1e2e
bspc config focused_border_color \#7480c2







bspc rule -a Bitwarden state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a discord monitor=DP-2 desktop=discord
bspc rule -a Steam monitor=DP-0 desktop=steam
bspc rule -a firefox monitor=DP-2 desktop=firefox 
bspc rule -a Alacritty monitor=DP-0 desktop=term
bspc rule -a Code monitor=DP=0 desktop=code
bspc rule -a Lutris monitor=DP-0 monitor=lutris
bspc rule -a gimp-2.10 monitor=DP-0 monitor=gimp
bspc rule -a bitwarden monitor=DP-2 monitor=X



corners() {
	bspc subscribe node_state | while read -r _ _ _ node state status; do
		if [[ "$state" == "floating" ]]; then
			case "$status" in
				off) xprop -id "$node" -remove _PICOM_CORNERS;;
				on) xprop -id "$node" -f _PICOM_CORNERS 32c -set _PICOM_CORNERS 1;;
			esac
		fi
	done
}



picom -b &
$HOME/.config/polybar/launch.sh &


nitrogen --restore &
/usr/bin/firefox -silent &
/usr/bin/discord &
/usr/games/steam -silent &
/usr/bin/alacritty &
/usr/games/lutris -silent &
/usr/bin/code &
/snap/bin/bitwarden -silent &

xsetroot -cursor_name left_ptr &
